### ISSUE TITLE
Does torchcast support  CUDA training?

### ISSUE THREAD

**Issue by PeterSH6** [strongio/torchcast#12]
Thanks for the great repo!

I want to implement a model with multivariate Kalman Filter and I find this repo. But I need to accelerate the computation on GPU. Does it support CUDA training and inferencing?

**Comment by jwdink** [comment]
Yep! you should be able to use `to()` just as you would for other pytorch applications. E.g.:

```python
maybe_cuda = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
my_model.to(maybe_cuda)
my_timeseries_dataset.to(maybe_cuda)
```
